- name: "Define the xcape service-start command, for external use"
  ansible.builtin.set_fact:
    xcape_start_cmd: "pkill -lx xcape; xcape -t {{ tap_key_timeout_ms }} -e '{{ mappings_arg_string }}'"
  vars:
    mappings_arg_string: "{{ mappings_strings_list | join (';') }}"
    mappings_strings_list: "{{ mappings_char_list | trim | split('\n') }}"
    mappings_char_list: |
      {% for item in tap_for_effect_mappings %}
      {{ item.tap_key }}={{ item.tap_effect }}
      {% endfor %}

